### ISSUE TITLE
 where are the json files?

### ISSUE THREAD

**Issue by valencebond** [TencentYoutuResearch/PersonReID-NAFS#1]
thanks for your code, but how can I get the  test_reid.json, train_reid.json, and val_reid.json

**Comment by valencebond** [comment]
I found the JSON files are generated by preprocess.py file but neglect some config parameters, such as args.load_split, args.load_vocab.

**Comment by girafffeee** [comment]
> I found the JSON files are generated by preprocess.py file but neglect some config parameters, such as args.load_split, args.load_vocab.

Sorry for the bad experience. We've added data.sh and modify preprocess.py to the repo. Details can be found in README.  Feel free to ask if you have any further questions.
