### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by RonanDou** [TencentYoutuResearch/PersonReID-NAFS#11]
Thank you very much for sharing. When I trained the model, I meet the same problem, and the performance of the model is only around 50%.

**Comment by wettera** [comment]
Thanks for your attention on our work. Is the environment the same as the following:

- `Python 3.7`
- `Pytorch 1.0.0 & torchvision 0.2.1`
- `numpy`
- `matplotlib (not necessary unless the need for the result figure)`
- `scipy 1.2.1`
- `pytorch_transformers 1.2.0`
