### ISSUE TITLE
Problems when run test.sh

### ISSUE THREAD

**Issue by ht374** [TencentYoutuResearch/PersonReID-NAFS#12]
First of all, thank you for sharing the code. But I have a bug running test.sh. I have a screenshot below. The bug is that best_model is being cast to an int. But I looked at model_path and there are only two files, model_best and best_model.pth.tar. There is nothing to convert to an int. Is there any problem with my file location?
![1616390619(1)](https://user-images.githubusercontent.com/80560853/111944331-5c59e700-8b12-11eb-8576-c862f1b85a2f.png)

**Comment by wettera** [comment]
> First of all, thank you for sharing the code. But I have a bug running test.sh. I have a screenshot below. The bug is that best_model is being cast to an int. But I looked at model_path and there are only two files, model_best and best_model.pth.tar. There is nothing to convert to an int. Is there any problem with my file location?
> ![1616390619(1)](https://user-images.githubusercontent.com/80560853/111944331-5c59e700-8b12-11eb-8576-c862f1b85a2f.png)

Thanks for your attention on our work. Please change `best_model.pth.tar ` to `10.pth.tar`, or you can change some code in the main function of `test.py`
