### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by HaeyeonPark** [TencentYoutuResearch/PersonReID-NAFS#14]
Hello, thanks for sharing your code! :> 
I have two questions.

1) I found out that in the uploaded training log, arguments given to "--part2" and "--part3" are 3 and 2 (not 2 and 3).
Is it just a typo?

2) As I have only TitanXP GPUs, when I run the code with 64 batches,  I got 'runtime: CUDA out of memory' error.
so I changed the batch size to 32 and it works. However, at 16 epochs suddenly loss increased and it did not decrease at all. 
Any idea about it? 
![image](https://user-images.githubusercontent.com/70568511/112310624-266e5b80-8ce8-11eb-9641-d37068384bd8.png)
I set the environment the same as you specified in the readme.

**Comment by wettera** [comment]
Thanks for your attention on our work.

1. Yes,  giving "--part2" and "--part3" 2 and 3 perhaps will get better results, you can have a try.
2. If change batch size, the learning rate should change simultaneously. So you can try a smaller learning rate.
