### ISSUE TITLE
Some confusion about the utilized jaccard distance in code

### ISSUE THREAD

**Issue by ZJWang9928** [TencentYoutuResearch/PersonReID-NAFS#3]
Thanks for your code, but I have some confusion about the Jaccard distance API used in your testing code.

https://github.com/TencentYoutuResearch/PersonReID-NAFS/blob/5301b8d95bb711f88357d71cff1a9aaaac76f473/utils/metric.py#L482

As we can see in [the document of SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.jaccard.html), `scipy.distance.jaccard` is used to `compute the Jaccard-Needham dissimilarity between two boolean 1-D arrays`. It seems that it is not the expected implementation of the Jaccard Distance in your paper. Is it ok to directly use this API?

**Comment by girafffeee** [comment]
> Thanks for your code, but I have some confusion about the Jaccard distance API used in your testing code.
> 
> https://github.com/TencentYoutuResearch/PersonReID-NAFS/blob/5301b8d95bb711f88357d71cff1a9aaaac76f473/utils/metric.py#L482
> 
> As we can see in [the document of SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.jaccard.html), `scipy.distance.jaccard` is used to `compute the Jaccard-Needham dissimilarity between two boolean 1-D arrays`. It seems that it is not the expected implementation of the Jaccard Distance in your paper. Is it ok to directly use this API?

Thank you very much. We fixed this bug [here](https://github.com/TencentYoutuResearch/PersonReID-NAFS/commit/71bf192f464a410845a88590e4660eeeba1a1e50)
