### ISSUE TITLE
Search for the baseline on BiLSTM

### ISSUE THREAD

**Issue by Jon-WZQ** [TencentYoutuResearch/PersonReID-NAFS#4]
Bert is hard for me to train, can you upload the baseline on BiLSTM. Thanks!

**Comment by Jon-WZQ** [comment]
Maybe you can just tell me the configuration of training BiLSTM and Resnet.

**Comment by oldcat-719** [comment]
> Maybe you can just tell me the configuration of training BiLSTM and Resnet.

Have you solved this problem? I hope to get your help.

**Comment by wettera** [comment]
> Maybe you can just tell me the configuration of training BiLSTM and Resnet.

Sorry for the late reply. Maybe you can try the following configuration:
`lr=0.00032
num_epoches=100
batch_size=128
lr_decay_ratio=0.9
epoches_decay=20_30_40`
It may not work, since I hardly use BiLSTM. Good luck.

**Comment by Jon-WZQ** [comment]
> > Maybe you can just tell me the configuration of training BiLSTM and Resnet.
> 
> Sorry for the late reply. Maybe you can try the following configuration:
> `lr=0.00032 num_epoches=100 batch_size=128 lr_decay_ratio=0.9 epoches_decay=20_30_40`
> It may not work, since I hardly use BiLSTM. Good luck.

Thanks a lot!
