### ISSUE TITLE
memory increased with steps

### ISSUE THREAD

**Issue by BrandonHanx** [TencentYoutuResearch/PersonReID-NAFS#6]
Hi all, @X-ing @girafffeee 

I found the memory increased with steps (about 20MB for several ten steps). This is not a good thing.
Did you encounter the same phenomenon?'

BTW, would you please take a little time to clean this repo?  The code is a little bit messy (too many unused variables and imports, no lint and so on)...

Thanks

**Comment by BrandonHanx** [comment]
What's more, would you please release the trained model? Because your random seed seems like non-fixed ...

**Comment by wettera** [comment]
> What's more, would you please release the trained model? Because your random seed seems like non-fixed ...

Thanks for your attention on our work. I have uploaded the trained model and the training log.
