### ISSUE TITLE
bert-base-uncased-vocab.txt' not found in model shortcut name list

### ISSUE THREAD

**Issue by yyll1998** [TencentYoutuResearch/PersonReID-NAFS#9]
I have downloaded  pretrained Resnet50 model, bert-base-uncased model and vocabulary to project_directory/pretrained/.But when i run train.sh,it showed that '**../pretrained/bert-base-uncased/bert-base-uncased-vocab.txt not found in model shortcut name list'**'.I attach the picture of the problem,please take a look at the problem.  Is it a problem with the file directory structure?Great thanks if get your help!
![image](https://user-images.githubusercontent.com/74692385/110192460-450bd000-7e69-11eb-98e7-6f3c12e4b4ce.png)

**Comment by wettera** [comment]
Thanks for your attention on our work. Please first run `cd project_directory/scripts`. Then run `sh train.sh`. If it doesn't work, please change `self.tokenizer = BertTokenizer.from_pretrained('../pretrained/bert-base-uncased/bert-base-uncased-vocab.txt')
        modelConfig = BertConfig.from_pretrained('../pretrained/bert-base-uncased/bert_config.json')
        self.textExtractor = BertModel.from_pretrained(
            '../pretrained/bert-base-uncased/pytorch_model.bin', config=modelConfig)` in `models/bert.py` to the absolute path.

**Comment by yyll1998** [comment]
First of all，thank you for your reply!But i'm sorry i have to disturb you again.I have changed it to the absolute path and the paths of the three files are the same.(I attatch  pictures below. ) But only the 'bert-base-uncased-vocab.txt' was not found. I don't know why there is such a problem.Thank you again.
![image](https://user-images.githubusercontent.com/74692385/110262790-ba091200-7fef-11eb-8aa7-554d8389b54c.png)
![image](https://user-images.githubusercontent.com/74692385/110263077-8aa6d500-7ff0-11eb-8d9d-95a10e6ef2da.png)
![image](https://user-images.githubusercontent.com/74692385/110263085-8f6b8900-7ff0-11eb-9c9a-975b5691759d.png)

**Comment by yyll1998** [comment]
Thank you for your reply! Under your guidance, I have solved this problem! Due to my mistake, I deleted the issues on gitbub by mistake. I'm very sorry! Thank you again!



At 2021-03-07 21:05:08, "wettera" ***@***.***> wrote:

Thanks for your attention on our work. Please first run cd project_directory/scripts. Then run sh train.sh. If it doesn't work, please change self.tokenizer = BertTokenizer.from_pretrained('../pretrained/bert-base-uncased/bert-base-uncased-vocab.txt') modelConfig = BertConfig.from_pretrained('../pretrained/bert-base-uncased/bert_config.json') self.textExtractor = BertModel.from_pretrained( '../pretrained/bert-base-uncased/pytorch_model.bin', config=modelConfig) in models/bert.py to the absolute path.
